// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_ornitholigist = "CgkIr4jp8OcREAIQBA"; // <GPGSID>
        public const string achievement_all_over_the_moon = "CgkIr4jp8OcREAIQBg"; // <GPGSID>
        public const string achievement_expert = "CgkIr4jp8OcREAIQBQ"; // <GPGSID>
        public const string achievement_birb_collector = "CgkIr4jp8OcREAIQCQ"; // <GPGSID>
        public const string achievement_first_try = "CgkIr4jp8OcREAIQAQ"; // <GPGSID>
        public const string leaderboard_best_score = "CgkIr4jp8OcREAIQAw"; // <GPGSID>
        public const string achievement_never_give_up = "CgkIr4jp8OcREAIQCg"; // <GPGSID>
        public const string achievement_one_giant_leap_for_birbkind = "CgkIr4jp8OcREAIQCA"; // <GPGSID>
        public const string achievement_risk_taker = "CgkIr4jp8OcREAIQDA"; // <GPGSID>
        public const string achievement_second_chance = "CgkIr4jp8OcREAIQCw"; // <GPGSID>
        public const string achievement_sky_is_not_the_limit = "CgkIr4jp8OcREAIQBw"; // <GPGSID>

}

